# fly.toml app configuration file generated for echo-rag on 2024-06-04T11:20:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'echo-rag'
primary_region = 'yyz'
swap_size_mb = 1024

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  swap_size_mb = 1024

